/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Fulladder (
  input A,
  input B,
  input Ci,
  output Co,
  output S
);
  assign S = ((A ^ B) ^ Ci);
  assign Co = ((A & B) | ((A | B) & Ci));
endmodule

module Sumador_4bits (
  input A1,
  input B1,
  input Ci,
  input A2,
  input B2,
  input A3,
  input B3,
  input A4,
  input B4,
  output S1,
  output S2,
  output S3,
  output S4,
  output Co
);
  wire s0;
  wire s5;
  wire s6;
  Fulladder Fulladder_i0 (
    .A( A1 ),
    .B( B1 ),
    .Ci( Ci ),
    .Co( s0 ),
    .S( S1 )
  );
  Fulladder Fulladder_i1 (
    .A( A2 ),
    .B( B2 ),
    .Ci( s0 ),
    .Co( s5 ),
    .S( S2 )
  );
  Fulladder Fulladder_i2 (
    .A( A3 ),
    .B( B3 ),
    .Ci( s5 ),
    .Co( s6 ),
    .S( S3 )
  );
  Fulladder Fulladder_i3 (
    .A( A4 ),
    .B( B4 ),
    .Ci( s6 ),
    .Co( Co ),
    .S( S4 )
  );
endmodule

module MedioRestador (
  input A,
  input B,
  output S,
  output C_out
);
  assign S = (A ^ B);
  assign C_out = (B & ~ A);
endmodule

module RestadorCompleto (
  input A,
  input B,
  input C_in,
  output S,
  output C_out
);
  assign C_out = (((B | C_in) & ~ A) | (C_in & B));
  assign S = (A ^ B ^ C_in);
endmodule

module Restador4bits (
  input A0,
  input B0,
  input A1,
  input B1,
  input A2,
  input B2,
  input A3,
  input B3,
  output S0,
  output S3,
  output C_0ut,
  output S1,
  output S2
);
  wire s4;
  wire s5;
  wire s6;
  MedioRestador MedioRestador_i0 (
    .A( A0 ),
    .B( B0 ),
    .S( S0 ),
    .C_out( s4 )
  );
  RestadorCompleto RestadorCompleto_i1 (
    .A( A1 ),
    .B( B1 ),
    .C_in( s4 ),
    .S( S1 ),
    .C_out( s5 )
  );
  RestadorCompleto RestadorCompleto_i2 (
    .A( A2 ),
    .B( B2 ),
    .C_in( s5 ),
    .S( S2 ),
    .C_out( s6 )
  );
  RestadorCompleto RestadorCompleto_i3 (
    .A( A3 ),
    .B( B3 ),
    .C_in( s6 ),
    .S( S3 ),
    .C_out( C_0ut )
  );
endmodule

module restSum (
  input A1,
  input A2,
  input A3,
  input A4,
  input B1,
  input B2,
  input B3,
  input B4,
  input Ci,
  input Ctrl,
  output S1,
  output S2,
  output S3,
  output C0,
  output S4
);
  wire s0;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  assign s6 = (Ci & Ctrl);
  assign s18 = (A1 & ~ Ctrl);
  assign s20 = (A2 & ~ Ctrl);
  assign s22 = (A3 & ~ Ctrl);
  assign s24 = (A4 & ~ Ctrl);
  assign s19 = (B1 & ~ Ctrl);
  assign s21 = (B2 & ~ Ctrl);
  assign s23 = (B3 & ~ Ctrl);
  assign s0 = (A1 & Ctrl);
  assign s7 = (A2 & Ctrl);
  assign s9 = (A3 & Ctrl);
  assign s11 = (A4 & Ctrl);
  assign s5 = (B1 & Ctrl);
  assign s8 = (B2 & Ctrl);
  assign s10 = (B3 & Ctrl);
  assign s12 = (B4 & Ctrl);
  assign s25 = (B4 & ~ Ctrl);
  Sumador_4bits Sumador_4bits_i0 (
    .A1( s0 ),
    .B1( s5 ),
    .Ci( s6 ),
    .A2( s7 ),
    .B2( s8 ),
    .A3( s9 ),
    .B3( s10 ),
    .A4( s11 ),
    .B4( s12 ),
    .S1( s13 ),
    .S2( s14 ),
    .S3( s15 ),
    .S4( s16 ),
    .Co( s17 )
  );
  Restador4bits Restador4bits_i1 (
    .A0( s18 ),
    .B0( s19 ),
    .A1( s20 ),
    .B1( s21 ),
    .A2( s22 ),
    .B2( s23 ),
    .A3( s24 ),
    .B3( s25 ),
    .S0( s26 ),
    .S3( s27 ),
    .C_0ut( s28 ),
    .S1( s29 ),
    .S2( s30 )
  );
  assign S1 = (s13 | s26);
  assign S2 = (s14 | s29);
  assign S3 = (s15 | s30);
  assign S4 = (s16 | s27);
  assign C0 = (s17 | s28);
endmodule
