/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module MedioRestador (
  input A,
  input B,
  output S,
  output C_out
);
  assign S = (A ^ B);
  assign C_out = (B & ~ A);
endmodule
