/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module RestadorCompleto (
  input A,
  input B,
  input C_in,
  output S,
  output C_out
);
  assign C_out = (((B | C_in) & ~ A) | (C_in & B));
  assign S = (A ^ B ^ C_in);
endmodule
